baseURL = 'https://xhh.netlify.app'
languageCode = 'en-US'
title = '灰灰的废话小站'
theme = 'hugo-geekdoc'

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

[params]
# geekdocLogo = "logo.png"